AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '*.gem'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
    - 'active_record_json_streamer.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'active_record_json_streamer.gemspec'

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 25

Metrics/MethodLength:
  Max: 50

Metrics/ParameterLists:
  Max: 10

Gemspec/DevelopmentDependencies:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/active_record_json_streamer.rb'
